name: CommonDevPack.DateTimeExtensions - Pack and Push to NuGet

on:
  push:
    branches: [ main ]

jobs:
  pack-push:
    env:
      PATH_PROJECT: ./src/CommonDevPack.Core.Extensions.DateTime/CommonDevPack.Core.Extensions.DateTime.csproj      

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.200

    - name: Generate Package 
      run: dotnet pack ${{ env.PATH_PROJECT }} -c Release -o out

    - name: Push to NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.APY_KEY_NUGET }} --source ${{ secrets.NUGET_SOURCE }} --skip-duplicate
